name: autobuild

on:
  schedule:
    - cron: '20 5 * * *'
  push:
    paths-ignore:
      - '*.zip'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'x86'
          - arch: 'x64'

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ilammy/setup-nasm@v1

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}

      - name: Build OpenSSL
        run: .scripts/autobuild.ps1

      - name: Pull the recent changes
        run: git pull

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated ${{matrix.arch}} build
          file_pattern: '*.zip'
