name: autobuild

on:
  schedule:
    - cron: '20 5 * * *'
  push:
    paths-ignore:
      - '*.zip'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'x86'
          - arch: 'x64'

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup nasm
        uses: ilammy/setup-nasm@v1

      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}

      - name: Build
        run: .scripts/autobuild.ps1

      - name: Pull
        run: git pull

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated ${{matrix.arch}} build
          file_pattern: '*.zip'
