name: autobuild

on:
  schedule:
    - cron: '20 5 * * *'
  push:
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'x86'
          - arch: 'x64'

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nasm
        uses: ilammy/setup-nasm@v1

      - name: Setup Visual Studio
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}

      - name: Build
        run: .scripts/autobuild.ps1

      - name: Deploy
        if: ${{github.ref == 'ref/heads/main'}}
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          if (Test-Path -Path *.zip) {
            $env:SSH_PRIVATE_KEY | Set-Content identity
            icacls identity /grant:r runneradmin:R /c
            icacls identity /inheritance:r /c
            scp -i identity -o StrictHostKeyChecking=no -o PasswordAuthentication=no *.zip ${{secrets.SSH_TARGET}}
          }
